### ISSUE TITLE
Error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by bgian** [mariusfeldmann/emoji-substitutions#2]
Just discovered this issue - maybe it's because I'm on El Capitan‎? 😔
<img width="682" alt="screen shot 2015-09-21 at 12 54 10 pm" src="https://cloud.githubusercontent.com/assets/3231370/9998590/f28c5958-605f-11e5-8cb7-c3eb6187c88c.png">

**Comment by mariusfeldmann** [comment]
Yeah probably. Will do some proper investigation once I get back from vacation. There has to be a better way to add them :v:

**Comment by bgian** [comment]
@mariusfeldmann sounds good 👌

**Comment by mariusfeldmann** [comment]
@bgian hey man! I found a much simpler way - check the repo page and let me know if it's works!

**Comment by bgian** [comment]
@mariusfeldmann works perfect, so much easier :+1:
